### ISSUE TITLE
Configure WAF for our Google AMP Fastly service

### ISSUE THREAD

**Issue by sjparkinson** [Financial-Times/google-amp#395]
We need to add and configure the Fastly WAF to this project's Fastly service.

The service ID is [`4g6XuZYa26LQSfxdzhXXMu`](https://manage.fastly.com/configure/services/4g6XuZYa26LQSfxdzhXXMu/).

[Fastly have published some documentation on how to configure their WAF on a service.](https://docs.fastly.com/guides/web-application-firewall/web-application-firewall)

We'll need to work with the Fastly support team to get this setup, you can raise an issue with them by posting in the [`#fastly-support` Slack channel](https://financialtimes.slack.com/messages/C2GFE1C9X) and adding a 🔑 emoji to the message.

We should first ensure that we are logging from Fastly to Splunk.

We should [configure a custom response that is a valid AMP page and matches this products design](https://docs.fastly.com/guides/web-application-firewall/web-application-firewall#customizing-the-response).

There is a command line tool Fastly are currently working on to configure a services WAF.

**Comment by quarterto** [comment]
I don't think the custom response being valid AMP is necessary. That would only be needed if 1. we expected Googlebot to be getting blocked and 2. we wanted the error page to be surfaced in Google search results

**Comment by sjparkinson** [comment]
We have updated the AMP production Fastly service to the latest WAF configuration set.

**Comment by sjparkinson** [comment]
Rules we are disabling:

* 931130
* 942100

**Comment by sjparkinson** [comment]
Todo, we need to check that the thresholds are sensible, then turn the rules on to block mode.

**Comment by sjparkinson** [comment]
From the Fastly support request the following tags where suggested, and I've added the loud rules as disabled.

```shell
waflyctl --apikey $FASTLY_TOKEN --serviceid 4g6XuZYa26LQSfxdzhXXMu --tags=owasp,application-multi --action log
waflyctl --apikey $FASTLY_TOKEN --serviceid 4g6XuZYa26LQSfxdzhXXMu --rules 4112031,4112012,4112030,4113002,931130,942100,941120,942390,920230,920300,942420 --action disabled
```

https://financialtimes.slack.com/archives/C2GFE1C9X/p1562931571121400

I disabled all existing rules (mainly the Wordpress specific ones) with:

```shell
waflyctl --apikey $FASTLY_TOKEN --serviceid 4g6XuZYa26LQSfxdzhXXMu --tags='language-html,language-htm,language-css,language-json,language-jpg,language-java,reputation-Malicious IP,reputation-Tor Exit Node,application-Wordpress' --action disabled
```

**Comment by sjparkinson** [comment]
We're turning on the WAF for Google AMP with:

```shell
waflyctl --apikey $FASTLY_TOKEN --serviceid 4g6XuZYa26LQSfxdzhXXMu --tags=owasp,application-multi --action block
```
