### ISSUE TITLE
Use new Change API since CRAPI is going away

### ISSUE THREAD

**Issue by nl-ria** [Financial-Times/google-amp#404]
Google AMP is one of very few systems left which is [using](https://github.com/Financial-Times/google-amp/blob/master/scripts/build/release.js#L7) Konstructor's Change Request API (CRAPI) to create release log into RemedyForce. Since CRAPI is hosted on-prem and is a really old and unmanaged java app, we plan to decommission it by the end of this quarter. 

To replace it, we have created a brand new and much nicer Change API which is much more simpler and reliable. More info [here](https://github.com/Financial-Times/change-api/blob/master/README.md#change-api---v2).

Please try it out ! ( ideally before the end of Q3)

**Comment by nl-ria** [comment]
Just a gentle nudge on this since we would like to decomm CRAPI soon-ish. cc @quarterto

**Comment by nl-ria** [comment]
Ah, looks like Google AMP is already [using](https://financialtimes.slack.com/archives/CGFP23JFL/p1569509394088400) the new Change API. I think this is because of [n-gage](https://github.com/Financial-Times/n-gage/pull/202) dependency. All that is needed is the clean-up I suppose? I am not sure how this plays into your build at all. Will your deploy break if [Konstructor's change request api](https://github.com/Financial-Times/google-amp/blob/master/scripts/build/release.js#L7) throws an error? 

We intend to turn off Konstructor's Change Request API by the end of October 2019.

**Comment by quarterto** [comment]
oh of course. yes, if the Konstructor request fails it will block the deploy. i'll remove that call ASAP. sorry it's taken me so long to get to this

**Comment by quarterto** [comment]
fixed by #407. thanks for the nudge
